spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Có thể dùng 'none', 'create', 'create-drop' tùy vào nhu cầu
    show-sql: true  # Hiển thị câu lệnh SQL trong log
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration  # Thư mục chứa các tệp migration
    baseline-on-migrate: true